### ISSUE TITLE
hey? are you and your project there?

### ISSUE THREAD

**Issue by zlataovce** [Andrew752/KarinAssistant#2]

**Comment by zlataovce** [comment]
hello, i'm trying to create ai assistant with the same name, but I create AI in Dialogflow. My job is semi-successful and you can look it up at: https://bot.dialogflow.com/karinassistant

**Comment by Andrew752** [comment]
Hey, Hello @zlataovce Sorry for late. Looks great but i always prefer coding in c# or python [in this purpose] it's more complicated but its more powerful and more stable (if you knew how to code in this languages) and you can do a lot more with making the program by yourself like playing music when you order that with your voice or opening something and many more. trust me i didn't know anything in programming but i learned everything with online courses and i'm now programming many programs in many languages. If you put it in your mind you can accomplish anything. And i hope for your project the full successful.

**Comment by zlataovce** [comment]
Hello! I am creating even better assistant in C++, link here: [https://github.com/zlataovce/autopilot-core](url) The same, I didn't know anything in programming, learned from online courses. My English may be a little bit messy, because I'm not a native speaker. Unfortunately, my assistant is console-based and not connected to any sound system, but that might change overtime. This all began when I was looking at your issue at andreiw's RaspberryPiPkg repository. Then I found your repository and began forming Autopilot. Thanks for the idea :)
